# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.53.1"

# skip creating README.md
skip_docs

default_platform :android

platform :android do

  lane :build_and_run_unit_tests_debug do
    gradle(
      task: 'clean assembleDebug testDebugUnitTest'
    )
  end

  lane :build_and_run_instrumentation_tests_debug do |options|
    emulator=options[:emulator]
    sh('./prepare-emulator.sh ' + emulator)

    gradle(
      task: 'clean assembleRelease connectedDebugAndroidTest'
    )

    sh('./kill-emulators.sh')
  end

  lane :build_and_run_unit_tests_release do |options|
    version=options[:version]
    versionCode=sh('./calc-version-code.sh ' + version)

    gradle(
      task: 'clean assembleRelease testReleaseUnitTest',

      properties: {
        'versionCode' => versionCode,
        'versionName' => version
      }
    )
  end

end
